Add the SecurityCoroutineContext class
Cosmo-Tech/cosmotech-api-common pull request #49
Opened 2022-12-19 15:48 UTC by mahkoCosmo

2022-12-26 09:53 UTC, vcarluer approved these changes
LGTM

2023-01-02 09:50 UTC, jreynard-code requested changes
LGTM!
Could you please upgrade the coroutines lib version ;)

2023-01-02 09:50 UTC, jreynard-code commented on build.gradle.kts
> +  implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.3-native-mt")
Could you please change for version 1.6.4 ? see [1.6.4](https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core/1.6.4)

2023-01-03 08:37 UTC, jreynard-code approved these changes
LGTM

2023-01-03 08:39 UTC, merged