Format query
Cosmo-Tech/cosmotech-api-common pull request #87
Opened 2023-04-21 16:39 UTC by icreated

2023-04-25 14:02 UTC, jreynard-code requested changes
Just some remarks about syntactic sugar and  add a test case with array property ;)

2023-04-25 14:02 UTC, jreynard-code commented on src/test/kotlin/com/cosmotech/api/utils/StringExtensionsTests.kt
> +    val map = mapOf("name" to "Joe Doe", "id" to "100", "object" to "{id:\"id\"}")
Could you please add a test with an array parameter please?

2023-04-26 06:39 UTC, icreated reviewed
Done

2023-04-26 08:07 UTC, jreynard-code approved these changes
LGTM :+1:

2023-04-26 08:07 UTC, merged